### ISSUE TITLE
The backend is empty because you haven't configured any Doctrine entity to manage.

### ISSUE THREAD

**Issue by gboyals** [alterphp/EasyAdminMongoOdmBundle#2]
Hello, fellow French developper !

I just started a Symfony 4 app with MongoDB ODM configured on it (the doc for it is horrible by the way), and I wanted to put an EasyAdmin on top of it. Problem is, I saw the GitHub issue [there](https://github.com/EasyCorp/EasyAdminBundle/issues/127#issuecomment-73940024) and a bit below, your answer.

I gave it a shot, installed it successfully but then, Symfony gives me this error : 
`The backend is empty because you haven't configured any Doctrine entity to manage. Solution: edit your configuration file (e.g. "config/packages/easy_admin.yaml") and configure the backend under the "easy_admin" key.`

I already modified the easy_admin.yaml file to put the config of easy_admin_mongo_odm, but no luck.

Here is my easy_admin.yaml file : 
```
easy_admin_mongo_odm:
    documents:
         User:
               class: App\Entity\User

easy_admin:
       design:
           menu: 
                 - { label: User, route: easyadmin_mongo_odm, params: { document: User } }
```
(Don't mind the App\Entity, I have my mongo Documents under src/Entity and so I kept the naming, but it's an actual document)

I also have this in my composer.json :
```
"alterphp/easyadmin-extension-bundle": "^2.0@dev",
"alterphp/easyadmin-mongo-odm-bundle": "dev-master",
        "easycorp/easyadmin-bundle": "^2.0@dev",

```
Do you know what could be the problem ?

Thanks in advance.

**Comment by alterphp** [comment]
EasyAdmin is an ORM centric admin bundle. It works only for Doctrine ORM **entities**. It requires at least 1 entity is defined under `easy_admin.entities` configuration.

EasyAdminMongoODMBundle is a bundle that relies on EasyAdmin to add the support of MongoODM documents, but it works along EasyAdmin.

So you have to create an ORM entity to make it work.

**Comment by gboyals** [comment]
I understood this, I was only missing the "at least one Entity" part, so thanks for the clarification !

It indeed had effect as I have a completely new error now : 
`An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "easyadmin_mongo_odm" as such route does not exist.").`

It seems to be provoked by the easy_admin_mongo_odm configuration.

Please excuse my noobiness, I'm a complete beginner in the PHP environment.

**Comment by alterphp** [comment]
You have to load the routes from the bundle. In YAML I do :

```
easy_admin_mongo_odm_bundle:
    resource: '@EasyAdminExtensionBundle/Controller/MongoOdmEasyAdminController.php'
    prefix: /admin/eao
    type: annotation
```

This bundle is experimental so that it does not provide friendly documentation. And moreover, I don't know haw it will evolve. I'm not sure I'm gonna maintain it for now.

**Comment by gboyals** [comment]
Thank you for taking the time to help me !
I feel like I'm almost there, I can now access the classical EasyAdmin Panel with my "User" Document and my dumb "DeliciousElephant" Entity, but the panel can't load the MongoDBBundle when I click my "User" document  :

`The DoctrineMongoDBBundle is not registered in your application. Try running "composer require doctrine/mongodb-odm-bundle".`

The "mongodb-odm-bundle" is in the composer.json and I can retrieve it via my DocumentManager, putting Users and removing them as well in my controller.
I also double-checked that I put it in "bundles.php".
I took a look at the code where you check for this bundle and it's exactly as I retrieve it in my controller : 
`        $dm = $this->get('doctrine_mongodb')->getManager();`

I'm a little confused about this error, as your code and mine seems in adequacy.

Regarding this bundle, it's a shame you won't maintain it in the future, I'm sure it can help others (like me :p). But I can also understand that it takes a lot of time and efforts...

A little edit for further information : I took the /admin/eao path you gave right above, and accessing it via the URL gives this : 
`Unable to generate a URL for the named route "" as such route does not exist.`
but clicking "User" in the panel redirects me to :
`admin/eao/?menuIndex=0&submenuIndex=-1&document=User`
which leads to the error mentioned earlier in this comment.

**Comment by alterphp** [comment]
I need more informations to help you. Can you post the stack trace please ?

**Comment by gboyals** [comment]
Of course ! Here is the stack trace given by Symfony : 
```
LogicException:
The DoctrineMongoDBBundle is not registered in your application. Try running "composer require doctrine/mongodb-odm-bundle".

  at vendor/alterphp/easyadmin-mongo-odm-bundle/src/Controller/EasyAdminController.php:362
  at AlterPHP\EasyAdminMongoOdmBundle\Controller\EasyAdminController->getMongoOdmDoctrine()
     (vendor/alterphp/easyadmin-mongo-odm-bundle/src/Controller/EasyAdminController.php:102)
  at AlterPHP\EasyAdminMongoOdmBundle\Controller\EasyAdminController->initialize(object(Request))
     (vendor/alterphp/easyadmin-mongo-odm-bundle/src/Controller/EasyAdminController.php:50)
  at AlterPHP\EasyAdminMongoOdmBundle\Controller\EasyAdminController->indexAction(object(Request))
     (vendor/symfony/http-kernel/HttpKernel.php:150)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:67)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:198)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:25)
```

Thanks again for your help !

**Comment by alterphp** [comment]
Do you use many kernels ? Can i see the content of bundles.php ?

**Comment by gboyals** [comment]
I only use one Kernel.php, which is at the root of my /src folder. I took it from the docs. Here it is : 
```
<?php

namespace App;

use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Component\Config\Loader\LoaderInterface;
use Symfony\Component\Config\Resource\FileResource;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Kernel as BaseKernel;
use Symfony\Component\Routing\RouteCollectionBuilder;

class Kernel extends BaseKernel
{
    use MicroKernelTrait;

    const CONFIG_EXTS = '.{php,xml,yaml,yml}';

    public function registerBundles()
    {
        $contents = require $this->getProjectDir().'/config/bundles.php';
        foreach ($contents as $class => $envs) {
            if ($envs[$this->environment] ?? $envs['all'] ?? false) {
                yield new $class();
            }
        }
    }

    protected function configureContainer(ContainerBuilder $container, LoaderInterface $loader)
    {
        $container->addResource(new FileResource($this->getProjectDir().'/config/bundles.php'));
        $container->setParameter('container.dumper.inline_class_loader', true);
        $confDir = $this->getProjectDir().'/config';

        $loader->load($confDir.'/{packages}/*'.self::CONFIG_EXTS, 'glob');
        $loader->load($confDir.'/{packages}/'.$this->environment.'/**/*'.self::CONFIG_EXTS, 'glob');
        $loader->load($confDir.'/{services}'.self::CONFIG_EXTS, 'glob');
        $loader->load($confDir.'/{services}_'.$this->environment.self::CONFIG_EXTS, 'glob');
    }

    protected function configureRoutes(RouteCollectionBuilder $routes)
    {
        $confDir = $this->getProjectDir().'/config';

        $routes->import($confDir.'/{routes}/*'.self::CONFIG_EXTS, '/', 'glob');
        $routes->import($confDir.'/{routes}/'.$this->environment.'/**/*'.self::CONFIG_EXTS, '/', 'glob');
        $routes->import($confDir.'/{routes}'.self::CONFIG_EXTS, '/', 'glob');
    }
}
```

And I, of course, registered the bundle in bundles.php : 
```
<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Doctrine\Bundle\MongoDBBundle\DoctrineMongoDBBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Symfony\Bundle\WebServerBundle\WebServerBundle::class => ['dev' => true],
    EasyCorp\Bundle\EasyAdminBundle\EasyAdminBundle::class => ['all' => true],
    AlterPHP\EasyAdminExtensionBundle\EasyAdminExtensionBundle::class => ['all' => true],
    AlterPHP\EasyAdminMongoOdmBundle\EasyAdminMongoOdmBundle::class => ['all' => true],
];
```

Sorry for the time, I lost all my previous config due to a git mistake I did but now I have it exactly like before, same errors.

**Comment by alterphp** [comment]
And the config file of doctrine_mongodb ?

**Comment by gboyals** [comment]
Yup, here it is. I use a mLab instance to prototype my project for now, I'll move for a standalone MongoDB on my server later on : 
```
doctrine_mongodb:
    auto_generate_proxy_classes: '%kernel.debug%'
    auto_generate_hydrator_classes: '%kernel.debug%'
    connections:
        default:
            server: 'mongodb://user:pass@ds029675.mlab.com:29675/my_db_name'
            options: {}
    default_database: 'my_db_name'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Entity'
                    prefix: App\Entity\
                    alias: App

```
I replaced `user`, `pass` and `my_db_name` to keep privacy of course. :) (Note that dir and prefix kept the App\Entity denomination even though User is a **Document**)

**Comment by alterphp** [comment]
I just pushed a modification that may fix your bug. Can you test it ?

**Comment by gboyals** [comment]
YAY, it works !!

I can now see the "User" panel, even though I can't see any users (there is none in my DB so that's fine), meaning that your fix worked !

I have to fix issues on my side and I'll keep you updated here.

Thank you so much for your work, you're a life-saver !
